name: Foundation Patterns Configuration Marketing
type: module
description: Pre-packaged Marketing Site building block kit configuration to jump start the use of the Foundation Patterns theme.
core: 8.x
package: User interface
dependencies:
  - foundation_patterns_config